# Generated by Django 2.1.2 on 2018-10-09 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RiskEnum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
            ],
            options={
                'ordering': ('field', 'value'),
            },
        ),
        migrations.CreateModel(
            name='RiskField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('api_type', models.TextField()),
            ],
            options={
                'ordering': ('risk_type', 'name'),
            },
        ),
        migrations.CreateModel(
            name='RiskInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RiskType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='RiskValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('risk_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskField')),
                ('risk_object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskInstance')),
            ],
        ),
        migrations.AddField(
            model_name='riskinstance',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskType'),
        ),
        migrations.AddField(
            model_name='riskfield',
            name='risk_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskType'),
        ),
        migrations.AddField(
            model_name='riskenum',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RiskField'),
        ),
        migrations.AddIndex(
            model_name='riskvalue',
            index=models.Index(fields=['risk_object'], name='api_riskval_risk_ob_60bc3e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='riskvalue',
            unique_together={('risk_object', 'risk_field')},
        ),
    ]
